### ISSUE TITLE
중앙일보 한방에 보는 그래픽 "돈보다 더 중요한 건 시간?"

### ISSUE THREAD

**Issue by bek9** [lexifdev/recharted#15]
[중앙일보 한방에 보는 그래픽 "돈보다 더 중요한 건 시간?"](https://www.facebook.com/joongang/photos/a.396063177103891.87834.155192444524300/1461892207187644/?type=3&theater)

![18815218_1461892207187644_9172753249878674470_o](https://cloud.githubusercontent.com/assets/11746585/26725318/f42c93f6-47d8-11e7-90b7-f7b20e9381a5.jpg)

1. "돈보다 더 중요한 건 시간?"을 말풍선처럼 표시하고 YES를 왼쪽에 표시하고 돈이 더 중요하다는 것을 오른쪽에 표시했는데 천천히 위에서부터 보지 않으면 처음 봤을 때 차트가 명확하게 뭘 의미하는지 알아보기 힘드네요. 차라리 단순히 시간이 더 중요하다 / 돈이 더 중요하다라고 나눴으면 보기 더 좋았을 것 같아요.

2. 돈과 시간의 양자택일 치고 중립 부분이 거의 대부분을 차지하는데, 무엇이 더 중요하다고 생각하는지 나타내는 것이 차트의 목적이라면 차라리 중립부분을 없애고 축을 가운데로 하는 butterfly chart가 더 효율적이지 않았을까 생각해 봅니다.

**Comment by raccoonyy** [comment]
날로 먹...;;

<img width="465" alt="screenshot 2017-06-07 21 07 07" src="https://user-images.githubusercontent.com/541274/26877588-5385e1f0-4bc5-11e7-963a-dbd36cc41983.png">

**Comment by cmygray** [comment]
![kakaotalk_photo_2017-06-07-21-19-06](https://user-images.githubusercontent.com/26966551/26878028-f5ac6fac-4bc6-11e7-9f2a-539ab27222ba.jpeg)

**Comment by KyoungRan** [comment]
![20170607_211947](https://user-images.githubusercontent.com/16181788/26878212-9d84b478-4bc7-11e7-8f1e-bc082804bcaf.jpg)
